#!/bin/bash
# Azure OAuth Configuration Fix Script

echo "=========================================="
echo "🔧 Azure OAuth Configuration Fixer"
echo "=========================================="
echo ""
echo "PROBLEM: AZURE_CLIENT_ID is set to 'inbox-sync-3' (incorrect)"
echo "SOLUTION: You need to replace it with your REAL Azure Application (client) ID"
echo ""
echo "=========================================="
echo "📋 HOW TO GET YOUR AZURE CLIENT ID"
echo "=========================================="
echo ""
echo "1. Go to: https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
echo "2. Find your app (BIQC / Strategy Squad / inbox-sync-3)"
echo "3. Click on it"
echo "4. Copy the 'Application (client) ID' (looks like: a1b2c3d4-e5f6-7890-abcd-ef1234567890)"
echo "5. Also get the 'Client Secret' (from Certificates & secrets tab)"
echo ""
echo "=========================================="
echo "⚠️  CURRENT INCORRECT VALUES"
echo "=========================================="
echo ""
echo "Backend .env file:"
grep "AZURE_CLIENT_ID\|AZURE_CLIENT_SECRET" /app/backend/.env
echo ""
echo "=========================================="
echo "✅ TO FIX THIS"
echo "=========================================="
echo ""
echo "Option 1: Provide me the real values and I'll update them"
echo "Option 2: Manually edit /app/backend/.env with:"
echo ""
echo "AZURE_CLIENT_ID=<your-real-azure-client-id>"
echo "AZURE_CLIENT_SECRET=<your-real-azure-client-secret>"
echo ""
echo "Then restart backend: sudo supervisorctl restart backend"
echo ""
echo "=========================================="
echo "🟢 SUPABASE EDGE FUNCTION SECRETS"
echo "=========================================="
echo ""
echo "After fixing backend .env, also update Supabase:"
echo ""
echo "Go to: Supabase Dashboard → Edge Functions → outlook-auth → Settings → Secrets"
echo ""
echo "Update these secrets:"
echo "  - AZURE_CLIENT_ID = <your-real-azure-client-id>"
echo "  - AZURE_CLIENT_SECRET = <your-real-azure-client-secret>"
echo ""
echo "=========================================="
