-- ═══════════════════════════════════════════════════════════════
-- INSIGHT OUTCOMES — Prediction Tracking Table
-- Phase 1: Instrumentation Only (no automated evaluation)
--
-- Purpose:
--   Store every prediction generated by biqc-insights-cognitive
--   Track timeframe, confidence, expected impact, metric source
--   Allow manual evaluation after 30-60 days of observation
--
-- Deploy: Run this SQL in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- 1. Create insight_outcomes table
create table if not exists public.insight_outcomes (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null,

  snapshot_id uuid references public.intelligence_snapshots(id) on delete cascade,

  prediction_type text not null, -- risk | growth | alignment | financial

  predicted_outcome text not null,

  predicted_timeframe_days integer not null,

  predicted_impact_low numeric,
  predicted_impact_high numeric,

  prediction_confidence numeric not null check (prediction_confidence >= 0 and prediction_confidence <= 100),

  metric_source text, -- crm | accounting | email | market | internal

  metric_reference text, -- e.g. pipeline_value, revenue_monthly, churn_rate

  action_required text,
  action_completed boolean default false,

  predicted_created_at timestamptz default now(),

  actual_outcome_metric numeric,
  actual_outcome_date timestamptz,

  outcome_delta numeric,
  accuracy_score numeric,

  evaluation_status text default 'pending', -- pending | evaluated | expired_no_data

  created_at timestamptz default now()
);

-- 2. Indexes for fast lookup
create index if not exists idx_insight_outcomes_user on public.insight_outcomes(user_id);
create index if not exists idx_insight_outcomes_snapshot on public.insight_outcomes(snapshot_id);
create index if not exists idx_insight_outcomes_status on public.insight_outcomes(evaluation_status);
create index if not exists idx_insight_outcomes_type on public.insight_outcomes(prediction_type);

-- 3. Add snapshot_confidence to intelligence_snapshots (feedback loop anchor)
alter table public.intelligence_snapshots
add column if not exists snapshot_confidence numeric;

-- 4. RLS policies
alter table public.insight_outcomes enable row level security;

create policy "Users can view own outcomes"
  on public.insight_outcomes for select
  using (auth.uid() = user_id);

create policy "Service role can insert outcomes"
  on public.insight_outcomes for insert
  with check (true);

create policy "Service role can update outcomes"
  on public.insight_outcomes for update
  using (true);
